import { useEffect, useState } from 'react';
import { CalendarDays, Clock3, Check, ArrowRight, UserRound, Mail, Stethoscope } from 'lucide-react';
const API = import.meta.env.VITE_API_URL || 'http://localhost:3333';
type Appointment = { id:number; patient_name:string; appointment_date:string; appointment_time:string };
const formatDate = (date:string) => new Intl.DateTimeFormat('pt-BR',{dateStyle:'long'}).format(new Date(`${date}T12:00:00`));
export default function App(){ const [date,setDate]=useState(''); const [slots,setSlots]=useState<string[]>([]); const [selected,setSelected]=useState(''); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [appointments,setAppointments]=useState<Appointment[]>([]); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [confirmed,setConfirmed]=useState(false);
 const loadAppointments=async()=>{try{const r=await fetch(`${API}/appointments`); if(r.ok)setAppointments(await r.json())}catch{setMessage('Não foi possível carregar as próximas consultas.')}};
 useEffect(()=>{loadAppointments()},[]); useEffect(()=>{if(!date){setSlots([]);return} setLoading(true);setSelected('');setMessage('');fetch(`${API}/available?date=${date}`).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);setSlots(body.available)}).catch(e=>{setSlots([]);setMessage(e.message)}).finally(()=>setLoading(false))},[date]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!date||!selected||!name.trim()){setMessage('Preencha a data, o horário e seu nome.');return}setLoading(true);setMessage('');try{const r=await fetch(`${API}/appointments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({patientName:name,patientEmail:email,date,time:selected})});const body=await r.json();if(!r.ok)throw new Error(body.error);setConfirmed(true);await loadAppointments();}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível confirmar o agendamento.')}finally{setLoading(false)}};
 if(confirmed)return <main className="shell"><header><div className="brand"><span className="brandmark"><Stethoscope size={19}/></span>CLINIC SCHEDULER</div><span className="timezone">Horário oficial: America/Sao_Paulo</span></header><section className="success card"><div className="successIcon"><Check/></div><p className="eyebrow">CONFIRMAÇÃO</p><h1>Agendamento confirmado!</h1><p>Sua consulta foi reservada com sucesso.</p><div className="summary"><b>{formatDate(date)}</b><span>{selected} — {String(Number(selected.slice(0,2))+1).padStart(2,'0')}:00</span><span>{name}</span></div><button onClick={()=>{setConfirmed(false);setDate('');setSelected('');setName('');setEmail('')}}>Novo agendamento <ArrowRight size={17}/></button></section></main>;
 return <main className="shell"><header><div className="brand"><span className="brandmark"><Stethoscope size={19}/></span>CLINIC SCHEDULER</div><span className="timezone">Horário oficial: America/Sao_Paulo</span></header><section className="hero"><p className="eyebrow">AGENDAMENTO INTELIGENTE</p><h1>Sua consulta,<br/><em>sem espera.</em></h1><p>Escolha uma data e veja apenas os horários realmente disponíveis.</p></section><div className="layout"><form className="card booking" onSubmit={submit}><Step n="01" title="ESCOLHA UMA DATA"><label>Data da consulta <CalendarDays size={17}/><input type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label></Step><Step n="02" title="HORÁRIOS DISPONÍVEIS"><div className="slots">{loading?<span className="muted">Consultando disponibilidade...</span>:slots.length?slots.map(s=><button type="button" className={selected===s?'selected':''} key={s} onClick={()=>setSelected(s)}><Clock3 size={15}/>{s}</button>):date&&!message?<span className="muted">Não existem mais horários disponíveis para esta data.</span>:!date?<span className="muted">Selecione uma data para consultar os horários.</span>:null}</div></Step><Step n="03" title="SEUS DADOS"><div className="fields"><label>Nome *<div className="input"><UserRound size={16}/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome completo" required/></div></label><label>E-mail<div className="input"><Mail size={16}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@exemplo.com"/></div></label></div></Step>{message&&<div className="alert">{message}</div>}<Step n="04" title="CONFIRMAÇÃO"><button className="primary" disabled={loading}>{loading?'Enviando...':'Confirmar agendamento'}<ArrowRight size={18}/></button></Step></form><aside><div className="asideTitle"><div><p className="eyebrow">AGENDA</p><h2>Próximas consultas</h2></div><CalendarDays size={22}/></div>{appointments.length?appointments.map(a=><div className="appointment" key={a.id}><span className="avatar">{a.patient_name.charAt(0).toUpperCase()}</span><div><b>{a.patient_name}</b><small>{new Intl.DateTimeFormat('pt-BR').format(new Date(`${a.appointment_date}T12:00:00`))} · {a.appointment_time}</small></div></div>):<p className="muted empty">Nenhum agendamento registrado.</p>}</aside></div><footer>Consultas com duração de 1 hora · Atendimento de segunda a sexta</footer></main>}
function Step({n,title,children}:{n:string,title:string,children:React.ReactNode}){return <section className="step"><div className="stepHead"><span>{n}</span><b>{title}</b></div>{children}</section>}
